version: "3.9"

services:
  influxdb:
    image: influxdb:latest
    ports:
      - "8086:8086"
    volumes:
      - ./influxdb2:/var/lib/influxdb2:rw
    environment:
      - DOCKER_INFLUXDB_INIT_USERNAME=root
      - DOCKER_INFLUXDB_INIT_PASSWORD=rootpassword
      - DOCKER_INFLUXDB_INIT_ORG=initorg
      - DOCKER_INFLUXDB_INIT_BUCKET=initorg
      - INFLUXDB_HTTP_AUTH_ENABLED="true"